In [1]:
# Imports and Data paths

import sys
import os
# Path追加
sys.path.append('../../')

import numpy as np
import cv2
import scipy.stats
import matplotlib.pyplot as plt
from mmdet.apis import init_detector, inference_detector
import configargparse
from typing import Any, Dict, List, Tuple, Optional
import warnings
from dataclasses import dataclass
from args import get_config
from data import Dataset
from common.visulaizations import draw_bb

configs = get_config("-c ../../configs/deepsort_notebook.ini")

In [2]:
from mmdetds import MMdetDS
from deepsort import DeepSort

REID_CKPT = "../..//weights/ckpt.t7"
MAX_DIST = 0.2
MIN_CONFIDENCE = 0.3
NMS_MAX_OVERLAP = 0.5
MAX_IOU_DISTANCE = 0.7
MAX_AGE = 70
N_INIT = 3
NN_BUDGET = 100
  

class_id = 2
dataset = Dataset(configs.data_dir, configs.result_dir,  fps=configs.fps)

total_imgs = len(dataset)
# detectionモデルのインスタンス化
detector = MMdetDS(configs=configs)

# trackingモデルのインスタンス化
deepsort = DeepSort(model_path=REID_CKPT,
                    max_dist=MAX_DIST,
                    min_confidence=MIN_CONFIDENCE,
                    nms_max_overlap=NMS_MAX_OVERLAP,
                    max_iou_distance=MAX_IOU_DISTANCE, 
                    max_age=MAX_AGE,
                    n_init=N_INIT,
                    nn_budget=NN_BUDGET,
                    device=configs.device)

# Inference using the model
for idx in range(0, total_imgs):
    print(f"Processing : {idx} / {total_imgs}")
    img_id = f"{idx:04d}"
    # out_filename = os.path.join(configs.result_dir, f"{idx}.png")
    img = dataset.get_images(idx)

    # detection
    bbox_xywh, cls_conf, cls_ids, bbox_result = detector(img)
    bbox_xywh = bbox_xywh[cls_ids == class_id]
    cls_conf = cls_conf[cls_ids == class_id]

    # tracking
    outputs = deepsort.update(bbox_xywh, cls_conf, img)



load checkpoint from local path: ../../weights/latest.pth
Processing : 0 / 35


/root/miniconda3/lib/python3.9/site-packages/mmdet/datasets/utils.py:66: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  warnings.warn(


[]
Processing : 1 / 35
[]
Processing : 2 / 35
[[659 532 759 645   1]
 [729 821 898 974   2]]
Processing : 3 / 35
[[660 545 767 667   1]
 [690 818 873 981   2]]
Processing : 4 / 35
[[ 662  570  774  701    1]
 [ 645  806  865 1001    2]]
Processing : 5 / 35
[[ 654  593  779  741    1]
 [ 605  786  858 1013    2]]
Processing : 6 / 35
[[ 647  630  778  785    1]
 [ 587  769  861 1021    2]]
Processing : 7 / 35
[[ 638  660  775  823    1]
 [ 597  764  871 1023    2]]
Processing : 8 / 35
[[ 626  689  770  859    1]
 [ 606  763  875 1024    2]]
Processing : 9 / 35
[[ 622  710  772  887    1]
 [ 613  759  879 1022    2]]
Processing : 10 / 35
[[ 600  740  762  937    1]
 [ 626  752  888 1017    2]]
Processing : 11 / 35
[[ 602  752  762  951    1]
 [ 637  760  889 1021    2]]
Processing : 12 / 35
[[ 612  749  767  946    1]
 [ 649  774  879 1018    2]]
Processing : 13 / 35
[[ 618  739  768  934    1]
 [ 650  768  876 1017    2]]
Processing : 14 / 35
[[ 626  740  771  930    1]
 [ 658  763  878 